export const CLINIC_INFO = {
  name: "SHREYAAN PHYSIOTHERAPY CENTER",
  shortName: "Shreyaan Physio",
  doctor: {
    name: "Dr. Sonam Maurya",
    qualification: "BPTh (Mumbai University)",
    registrationNo: "10534",
    title: "Senior Consultant Physiotherapist",
    experience: "10+ Years Clinical Experience",
    specializations: [
      "Dry Needling",
      "Cupping Therapy",
      "Therapeutic Taping",
      "Ayurvedic Diet & Nutrition",
      "Orthopaedic Rehabilitation",
      "Neurological Rehabilitation",
    ],
  },
  contact: {
    primaryPhone: "+919140574645",
    primaryPhoneDisplay: "+91 9140574645",
    secondaryPhone: "+919410230235",
    secondaryPhoneDisplay: "+91 9410230235",
    whatsappPhone: "919140574645",
    email: "shreyaanphysiotherapycenter@gmail.com",
    address: {
      street: "NTPC Road, near Ganda Nala",
      locality: "Unchahar",
      district: "Raebareli",
      state: "Uttar Pradesh",
      postalCode: "229406",
      country: "IN",
      fullAddress: "NTPC Road, near Ganda Nala, Unchahar, Uttar Pradesh 229406",
    },
    geo: {
      latitude: 25.9077702,
      longitude: 81.2966576,
    },
    openingHours: [
      { days: "Monday - Sunday", hours: "10:00 AM - 06:00 PM" },
    ],
    openingHoursRaw: "Mo-Su 10:00-18:00",
  },
  urls: {
    siteUrl: process.env.NEXT_PUBLIC_SITE_URL || "https://shreyaanphysiotherapycenter.in",
    googleMap: "https://www.google.com/maps/place/SHREYAAN+PHYSIOTHERAPY+CENTER/@25.907775,81.2940827,17z/data=!3m1!4b1!4m6!3m5!1s0x399b0f869997b4e3:0xf5adf7c9c63088c3!8m2!3d25.9077702!4d81.2966576!16s%2Fg%2F11svgg3587?hl=en-US&entry=ttu",
    googleMapEmbed: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3596.790938676241!2d81.2940827!3d25.907775!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x399b0f869997b4e3%3A0xf5adf7c9c63088c3!2sSHREYAAN%20PHYSIOTHERAPY%20CENTER!5e0!3m2!1sen!2sin!4v1700000000000!5m2!1sen!2sin",
    googleDirections: "https://www.google.com/maps/dir/?api=1&destination=25.9077702,81.2966576&destination_place_id=0x399b0f869997b4e3:0xf5adf7c9c63088c3",
    googleWriteReview: "https://search.google.com/local/writereview?placeid=SHREYAAN+PHYSIOTHERAPY+CENTER",
    facebook: "https://www.facebook.com/ShreyaanPhysiotherapyCentre/",
    instagram: "https://www.instagram.com/shreyaanphysiotherapycenter/",
    doctorInstagram: "https://www.instagram.com/sonam.mourya.7503/",
  },
};

export const SERVICES = [
  {
    id: "back-neck-pain",
    title: "Back & Neck Pain Rehabilitation",
    description: "Evidence-led care to eliminate pain, correct posture, and help you move with confidence.",
    category: "Spine Care",
    iconName: "Activity",
    highlights: ["Spine decompression", "Posture retraining", "Targeted core strengthening"],
  },
  {
    id: "knee-joint-pain",
    title: "Knee & Joint Pain Management",
    description: "Restore comfortable movement, improve joint flexibility, and regain daily independence.",
    category: "Joint Care",
    iconName: "Activity",
    highlights: ["Arthritis management", "Ligament rehab", "Joint mobilization"],
  },
  {
    id: "sciatica-slip-disc",
    title: "Slip Disc & Sciatica Care",
    description: "Focused non-surgical rehabilitation for nerve compression, radiating pain, and disc recovery.",
    category: "Neuromuscular",
    iconName: "Zap",
    highlights: ["Nerve gliding exercises", "Lumbar traction", "Pain desensitization"],
  },
  {
    id: "sports-injury",
    title: "Sports Injury Rehabilitation",
    description: "Tailored return-to-activity programs built around performance, strength, and injury prevention.",
    category: "Sports Rehab",
    iconName: "Trophy",
    highlights: ["Biomechanical assessment", "Athletic conditioning", "Agility restoration"],
  },
  {
    id: "paralysis-rehab",
    title: "Paralysis & Neuro Rehab",
    description: "Compassionate, progressive support for stroke, neuropathy, and motor skill recovery.",
    category: "Neuro Rehab",
    iconName: "Brain",
    highlights: ["Motor re-education", "Balance training", "Functional independence"],
  },
  {
    id: "post-surgery-rehab",
    title: "Post-Surgical Rehabilitation",
    description: "Structured, phase-by-phase recovery following orthopaedic, spinal, or joint replacement surgeries.",
    category: "Post-Op Care",
    iconName: "ShieldPlus",
    highlights: ["Scar tissue therapy", "Range-of-motion recovery", "Strength restoration"],
  },
  {
    id: "dry-needling-cupping",
    title: "Dry Needling & Cupping Therapy",
    description: "Modern evidence-based adjunct therapies for rapid trigger point release and circulation support.",
    category: "Specialized Therapy",
    iconName: "Sparkles",
    highlights: ["Myofascial release", "Pain relief", "Enhanced tissue healing"],
  },
  {
    id: "electrotherapy-taping",
    title: "Electrotherapy & K-Taping",
    description: "Targeted electrical stimulation, ultrasound modalities, and kinesiology taping to speed healing.",
    category: "Advanced Modalities",
    iconName: "Cpu",
    highlights: ["TENS & IFT therapy", "Kinesiology taping", "Edema reduction"],
  },
];

export const FAQ_ITEMS = [
  {
    question: "Do I need a doctor's referral to visit Shreyaan Physiotherapy Center?",
    answer: "No referral is required. You can book an appointment directly with Dr. Sonam Maurya for a comprehensive assessment and personalized treatment plan.",
  },
  {
    question: "What qualifications does Dr. Sonam Maurya hold?",
    answer: "Dr. Sonam Maurya holds a Bachelor of Physiotherapy (BPTh) degree from Mumbai University (Registration No: 10534) with advanced certifications in dry needling, cupping, taping, and clinical nutrition.",
  },
  {
    question: "What should I bring to my first appointment?",
    answer: "Please bring any relevant medical reports, X-rays, MRI scans, current prescriptions, and wear loose, comfortable clothing for physical evaluation.",
  },
  {
    question: "How long is each physiotherapy session?",
    answer: "Initial consultation and evaluation usually take 45–60 minutes. Subsequent treatment sessions typically range between 30–50 minutes depending on your treatment plan.",
  },
  {
    question: "Are dry needling and cupping therapy available?",
    answer: "Yes! Dr. Sonam Maurya is certified in dry needling and cupping therapy. These advanced modalities are incorporated when clinically indicated for maximum pain relief.",
  },
  {
    question: "Where is the clinic located in Unchahar?",
    answer: "We are conveniently located on NTPC Road, near Ganda Nala, Unchahar, Uttar Pradesh 229406. Parking and wheelchair access are available.",
  },
  {
    question: "Can physiotherapy help avoid knee replacement surgery?",
    answer: "In mild to moderate osteoarthritis, structured quadriceps strengthening and joint mobilization can significantly relieve pain, improve mobility, and defer surgical intervention.",
  },
  {
    question: "Is non-surgical treatment possible for a slip disc or sciatica?",
    answer: "Yes! Over 90% of herniated disc and sciatica cases respond successfully to conservative physical therapy, mechanical decompression, and nerve flossing exercises.",
  },
  {
    question: "What are the clinic working hours?",
    answer: "The clinic is open 7 days a week from Monday to Sunday, 10:00 AM to 6:00 PM.",
  },
  {
    question: "How many sessions will I need for complete recovery?",
    answer: "Session count varies by condition. Acute strains may require 4 to 6 sessions, while chronic back pain, stroke paralysis, or post-surgical rehab may require 10 to 20+ sessions.",
  },
  {
    question: "Is dry needling painful?",
    answer: "Most patients feel only a minor prick followed by a temporary muscle twitch response. It is very well tolerated and provides rapid muscular release.",
  },
  {
    question: "Do you offer post-stroke paralysis rehabilitation?",
    answer: "Yes. We offer specialized neurological rehabilitation utilizing neuro-developmental therapy (NDT), PNF stretching, and functional electrical stimulation (FES).",
  },
  {
    question: "Can I book an appointment via WhatsApp?",
    answer: "Yes! Click the WhatsApp button on our website or text +91 9140574645 to request your preferred date and time slot.",
  },
  {
    question: "When should post-surgical physiotherapy begin after joint replacement?",
    answer: "Physiotherapy typically begins within 24 to 48 hours post-surgery as advised by your orthopaedic surgeon to prevent stiffness and blood clots.",
  },
  {
    question: "What electrotherapy modalities are available at the clinic?",
    answer: "We use Interferential Therapy (IFT), TENS, Therapeutic Ultrasound, Muscle Stimulator, and Kinesiology Taping.",
  },
  {
    question: "Is physiotherapy safe during pregnancy?",
    answer: "Yes, specialized pre-natal and post-natal physiotherapy is safe and effectively relieves pelvic and lower back pain during pregnancy.",
  },
  {
    question: "How does cupping therapy improve muscle recovery?",
    answer: "Cupping therapy creates negative pressure suction to pull fresh blood supply to tight fascia, breaking down muscle adhesions and releasing stagnant metabolic waste.",
  },
  {
    question: "What is kinesiology taping and how long does it stay on?",
    answer: "K-taping is elastic therapeutic taping that supports weak joints and improves lymphatic flow. It stays on skin comfortably for 3 to 5 days even while showering.",
  },
  {
    question: "Do you provide guidance for home exercises?",
    answer: "Yes! Every patient receives an individualized home exercise program with posture rules to maintain progress between clinic visits.",
  },
  {
    question: "Can physiotherapy relieve tension headaches originating from neck stiffness?",
    answer: "Absolutely. Cervicogenic headaches caused by upper neck muscle tightness are effectively resolved with cervical spine mobilization and muscle trigger release.",
  },
  {
    question: "What is frozen shoulder and how is it treated?",
    answer: "Frozen shoulder (adhesive capsulitis) causes severe shoulder stiffness. We treat it through capsular stretching, ultrasound therapy, and progressive range-of-motion exercises.",
  },
  {
    question: "Do you treat sports injuries like ankle sprains or hamstring pulls?",
    answer: "Yes! We provide sports rehabilitation including acute RICE care, cross-friction massage, agility drills, and return-to-sport clearance testing.",
  },
  {
    question: "What is the difference between dry needling and acupuncture?",
    answer: "Dry needling focuses on anatomical muscle trigger points based on Western neuroanatomy, while traditional acupuncture follows Eastern energy meridians.",
  },
  {
    question: "How can I prevent back pain from desk work?",
    answer: "Maintain a 90-degree knee/hip angle, position your screen at eye level, use lumbar cushion support, and take 2-minute movement breaks every 45 minutes.",
  },
  {
    question: "Are treatments safe for senior citizens?",
    answer: "Yes. Dr. Sonam Maurya customizes gentle, low-impact joint mobilization and balance training specially tailored to senior bone density and comfort.",
  },
  {
    question: "What payments are accepted at the clinic?",
    answer: "We accept Cash, UPI (Google Pay, PhonePe, Paytm), and major online bank transfers.",
  },
  {
    question: "Is emergency appointment consultation available?",
    answer: "For acute severe pain or sudden muscle spasms, call +91 9140574645 directly for priority same-day scheduling.",
  },
  {
    question: "What should I do if my pain increases after a session?",
    answer: "Mild soreness for 12–24 hours after deep muscle work is normal as tissue heals. Applying ice packs for 15 minutes helps soothe local soreness.",
  },
  {
    question: "Does the clinic follow hygiene and sanitization standards?",
    answer: "Yes! Treatment couches, needles, and equipment pads are thoroughly sanitized between every single patient session for 100% hygiene safety.",
  },
  {
    question: "How do I reach the clinic from Raebareli or NTPC Unchahar?",
    answer: "We are located right on NTPC Road near Ganda Nala in Unchahar, easily accessible by car, auto, or public transport.",
  },
];

export const TRANSLATIONS = {
  en: {
    nav: {
      home: "Home",
      about: "About",
      services: "Services",
      gallery: "Gallery",
      blog: "Blog",
      reviews: "Testimonials",
      faq: "FAQ",
      contact: "Contact",
      doctorLogin: "Doctor Login",
      bookAppointment: "Book Appointment",
      callNow: "Call Now",
    },
    hero: {
      badge: "Top-Rated Physiotherapy Clinic in Unchahar",
      title: "Move Better. Live Pain-Free.",
      subtitle: "Expert, compassionate physiotherapy & advanced rehabilitation by Dr. Sonam Maurya. Restoring movement, independence, and vital energy.",
      ctaPrimary: "Book An Appointment",
      ctaSecondary: "Call Clinic",
      trustStat1: "10+ Years Care",
      trustStat2: "157+ 5-Star Reviews",
      trustStat3: "Certified Specialist",
    },
    quickInfo: {
      hoursTitle: "Clinic Hours",
      hoursText: "Mon – Sun: 10:00 AM – 6:00 PM",
      locationTitle: "Location",
      locationText: "NTPC Road, Unchahar, UP",
      contactTitle: "Call Us",
      contactText: "+91 9140574645",
    },
    about: {
      eyebrow: "ABOUT THE CLINIC & DOCTOR",
      title: "Holistic, Patient-Centered Physical Care",
      text: "At Shreyaan Physiotherapy Center, recovery is built around your individual life and goals. Dr. Sonam Maurya combines Mumbai University clinical expertise with advanced therapeutic modalities.",
      feature1Title: "Evidence-Based Diagnosis",
      feature1Desc: "Comprehensive functional evaluation before beginning any rehabilitation program.",
      feature2Title: "Modern Modalities",
      feature2Desc: "Certified in dry needling, cupping, therapeutic taping, and electrotherapy.",
      feature3Title: "Personalized Care Plans",
      feature3Desc: "Tailored one-on-one sessions aimed at long-term prevention and lasting relief.",
    },
    services: {
      eyebrow: "OUR SPECIALIZED SERVICES",
      title: "Targeted Treatments for Every Stage of Recovery",
      text: "Whether you are recovering from surgery, managing chronic joint pain, or rehabilitating a sports injury, we offer evidence-guided care.",
      bookService: "Book This Treatment",
    },
    gallery: {
      eyebrow: "OUR CLINIC ENVIRONMENT",
      title: "A Clean, Healing Atmosphere Designed For Your Comfort",
      text: "Equipped with modern therapeutic modalities in a tranquil, hygienic clinical setting.",
    },
    reviews: {
      eyebrow: "PATIENT VERIFIED REVIEWS",
      title: "Trusted by Hundreds of Patients in Unchahar & Raebareli",
      subtitle: "Real Google Business Profile reviews automatically synchronized.",
      writeReview: "Write a Review",
      viewAllReviews: "View All on Google",
      verifiedPatient: "Verified Google Patient",
    },
    faq: {
      eyebrow: "FREQUENTLY ASKED QUESTIONS",
      title: "Everything You Need to Know Before Your Visit",
    },
    contact: {
      eyebrow: "GET IN TOUCH",
      title: "Start Your Recovery Journey Today",
      text: "Fill out the quick appointment request form or reach out via WhatsApp/Call for immediate assistance.",
      formTitle: "Request An Appointment",
      namePlaceholder: "Your Full Name",
      phonePlaceholder: "Your Phone Number",
      datePlaceholder: "Preferred Date",
      timePlaceholder: "Preferred Time",
      servicePlaceholder: "Select Service / Concern",
      messagePlaceholder: "Briefly describe your symptoms or concern (optional)",
      submitBtn: "Send Appointment Request",
      whatsappDirect: "Chat Directly on WhatsApp",
      successTitle: "Appointment Request Received!",
      successMessage: "We have opened WhatsApp with your details. Click send to confirm your appointment time.",
    },
    footer: {
      tagline: "Dedicated to restoring your mobility, strength, and quality of life.",
      quickLinks: "Quick Navigation",
      legalDisclaimer: "Medical Disclaimer: Information provided on this website is for educational purposes and should not replace professional medical consultation.",
      rights: "All Rights Reserved.",
      designedBy: "Designed & Developed by",
    },
  },
  hi: {
    nav: {
      home: "मुख्य पृष्ठ",
      about: "हमारे बारे में",
      services: "सेवाएं",
      gallery: "गैलरी",
      blog: "ब्लॉग",
      reviews: "समीक्षाएं",
      faq: "सवाल-जवाब",
      contact: "संपर्क करें",
      doctorLogin: "डॉक्टर लॉगिन",
      bookAppointment: "अपॉइंटमेंट लें",
      callNow: "कॉल करें",
    },
    hero: {
      badge: "ऊंचाहार का प्रमुख फिजियोथेरेपी केंद्र",
      title: "बेहतर चलें। दर्द-मुक्त जिएं।",
      subtitle: "डॉ. सोनम मौर्य द्वारा विशेषज्ञ और संवेदनशील फिजियोथेरेपी। आपकी गतिशीलता, शक्ति और आत्मविश्वास की पुनः प्राप्ति।",
      ctaPrimary: "अपॉइंटमेंट बुक करें",
      ctaSecondary: "क्लिनिक को कॉल करें",
      trustStat1: "10+ वर्ष का अनुभव",
      trustStat2: "157+ 5-स्टार समीक्षाएं",
      trustStat3: "प्रमाणित विशेषज्ञ",
    },
    quickInfo: {
      hoursTitle: "क्लिनिक का समय",
      hoursText: "सोमवार – रविवार: 10:00 AM – 6:00 PM",
      locationTitle: "स्थान",
      locationText: "एनटीपीसी रोड, ऊंचाहार, यूपी",
      contactTitle: "संपर्क करें",
      contactText: "+91 9140574645",
    },
    about: {
      eyebrow: "क्लिनिक और डॉक्टर के बारे में",
      title: "आपकी संपूर्ण सेहत पर केंद्रित फिजियोथेरेपी देखभाल",
      text: "श्रेयान फिजियोथेरेपी सेंटर में हर मरीज के लिए व्यक्तिगत देखभाल योजना बनाई जाती है। डॉ. सोनम मौर्य (मुंबई यूनिवर्सिटी) सही निदान और आधुनिक तकनीकों का उपयोग करती हैं।",
      feature1Title: "सटीक शारीरिक परीक्षण",
      feature1Desc: "उपचार शुरू करने से पहले विस्तृत जांच एवं मूल्यांकन।",
      feature2Title: "आधुनिक उपचार पद्धतियाँ",
      feature2Desc: "ड्राई नीडलिंग, कपिंग थेरेपी, के-टैपिंग और इलेक्ट्रोथेरेपी में विशेषज्ञता।",
      feature3Title: "व्यक्तिगत रिकवरी प्लान",
      feature3Desc: "लंबे समय तक दर्द से राहत और रोकथाम के लिए समर्पित सत्र।",
    },
    services: {
      eyebrow: "हमारी विशेष सेवाएं",
      title: "आपकी रिकवरी के हर चरण के लिए विशेषज्ञ उपचार",
      text: "चाहे कमर दर्द हो, घुटने का दर्द, पैरालिसिस या सर्जरी के बाद की रिकवरी — हम हर स्थिति का सही इलाज प्रदान करते हैं।",
      bookService: "यह उपचार बुक करें",
    },
    gallery: {
      eyebrow: "क्लिनिक का वातावरण",
      title: "स्वच्छ और आरामदायक वातावरण",
      text: "आधुनिक फिजियोथेरेपी उपकरणों से सुसज्जित एक स्वच्छ और शांत वातावरण।",
    },
    reviews: {
      eyebrow: "मरीजों की सत्यापित समीक्षाएं",
      title: "ऊंचाहार और रायबरेली के सैकड़ों मरीजों का भरोसा",
      subtitle: "गूगल बिजनेस प्रोफाइल से स्वचालित रूप से सिंक की गई प्रामाणिक समीक्षाएं।",
      writeReview: "समीक्षा लिखें",
      viewAllReviews: "गूगल पर सभी समीक्षाएं देखें",
      verifiedPatient: "सत्यापित गूगल मरीज",
    },
    faq: {
      eyebrow: "अक्सर पूछे जाने वाले प्रश्न",
      title: "आपकी यात्रा से पहले आवश्यक जानकारी",
    },
    contact: {
      eyebrow: "संपर्क करें",
      title: "आज ही अपनी रिकवरी यात्रा शुरू करें",
      text: "अपॉइंटमेंट फॉर्म भरें या तुरंत सहायता के लिए व्हाट्सएप/कॉल के माध्यम से संपर्क करें।",
      formTitle: "अपॉइंटमेंट का अनुरोध करें",
      namePlaceholder: "आपका पूरा नाम",
      phonePlaceholder: "आपका फोन नंबर",
      datePlaceholder: "पसंदीदा तारीख",
      timePlaceholder: "पसंदीदा समय",
      servicePlaceholder: "सेवा / समस्या चुनें",
      messagePlaceholder: "अपनी समस्या का संक्षेप में वर्णन करें (वैकल्पिक)",
      submitBtn: "अनुरोध भेजें",
      whatsappDirect: "व्हाट्सएप पर तुरंत बात करें",
      successTitle: "अनुरोध प्राप्त हुआ!",
      successMessage: "हमने व्हाट्सएप खोला है। अपॉइंटमेंट की पुष्टि के लिए सेंड दबाएं।",
    },
    footer: {
      tagline: "आपकी गतिशीलता, शक्ति और जीवन की गुणवत्ता को बहाल करने के लिए समर्पित।",
      quickLinks: "त्वरित नेविगेशन",
      legalDisclaimer: "चिकित्सा अस्वीकरण: इस वेबसाइट पर दी गई जानकारी केवल शैक्षणिक उद्देश्यों के लिए है और इसे डॉक्टर की सलाह का विकल्प न माना जाए।",
      rights: "सर्वाधिकार सुरक्षित।",
      designedBy: "डिजाइन और विकसित द्वारा",
    },
  },
};
